# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CCzEiaY-s6fTnqWtfy9qIhDvMkmL7iQM
"""

#!/usr/bin/env python3
"""
Reproducible stats pipeline for:
"Complexity-associated representation changes in clinical language models..."

Inputs:
- results_complete_with_cosine.csv  (per-text)
- summary_with_cosine.csv           (optional sanity check)

Outputs (prints to console and saves CSV tables):
- anova_table.csv
- welch_simple_vs_complex.csv
- bootstrap_ci_simple_vs_complex.csv
- kw_table.csv
- length_controls_group3_group4.csv

Dependencies:
pip install pandas numpy scipy statsmodels
"""

from __future__ import annotations

import math
import numpy as np
import pandas as pd

from scipy import stats

# -----------------------------
# Config
# -----------------------------
RESULTS_CSV = "results_complete_with_cosine.csv"
SUMMARY_CSV = "summary_with_cosine.csv"  # optional
OUTDIR = "stats_outputs"

MODELS = ["gpt2", "gpt2-medium", "gpt2-xl", "bert", "biobert", "clinicalbert", "llama2", "mistral"]

# Group labels used in your CSV
G1 = {"simple": "g1s", "moderate": "g1m", "complex": "g1c"}
G2 = {"simple": "g2s", "moderate": "g2m", "complex": "g2c"}
G3 = {"short": "g3ms", "long": "g3cs"}  # Synthetic length control
G4 = {"short": "g4ms", "long": "g4cs"}  # Real padded length control

ALPHA_FAMILY = 0.05
BONFERRONI_M = len(MODELS)
ALPHA_BONF = ALPHA_FAMILY / BONFERRONI_M  # 0.00625

BOOTSTRAP_B = 10000
RNG_SEED = 0

np.random.seed(RNG_SEED)


# -----------------------------
# Helpers
# -----------------------------
def ensure_outdir(path: str) -> None:
    import os
    os.makedirs(path, exist_ok=True)


def cohen_d_independent(x: np.ndarray, y: np.ndarray) -> float:
    """
    Cohen's d for independent samples using pooled SD.
    (Commonly used; if you used a different variant, swap here.)
    """
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    nx, ny = len(x), len(y)
    if nx < 2 or ny < 2:
        return np.nan
    sx2 = np.var(x, ddof=1)
    sy2 = np.var(y, ddof=1)
    sp = math.sqrt(((nx - 1) * sx2 + (ny - 1) * sy2) / (nx + ny - 2))
    if sp == 0:
        return np.nan
    return (np.mean(y) - np.mean(x)) / sp


def eta_squared_oneway(*groups: np.ndarray) -> float:
    """
    η² = SS_between / SS_total for one-way ANOVA.
    """
    groups = [np.asarray(g, dtype=float) for g in groups]
    all_vals = np.concatenate(groups)
    grand_mean = np.mean(all_vals)
    ss_total = np.sum((all_vals - grand_mean) ** 2)
    ss_between = sum(len(g) * (np.mean(g) - grand_mean) ** 2 for g in groups)
    if ss_total == 0:
        return np.nan
    return ss_between / ss_total


def percent_change(a: float, b: float) -> float:
    """Percent change from a to b."""
    return ((b - a) / a) * 100.0


def bootstrap_percent_change_ci(x: np.ndarray, y: np.ndarray, b: int = BOOTSTRAP_B) -> tuple[float, float]:
    """
    Bootstrap 95% CI for percent change in mean from x (baseline) to y (comparison).
    """
    rng = np.random.default_rng(RNG_SEED)
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    nx, ny = len(x), len(y)
    if nx == 0 or ny == 0:
        return (np.nan, np.nan)

    idx_x = rng.integers(0, nx, size=(b, nx))
    idx_y = rng.integers(0, ny, size=(b, ny))
    mx = x[idx_x].mean(axis=1)
    my = y[idx_y].mean(axis=1)
    pc = (my - mx) / mx * 100.0
    lo = np.percentile(pc, 2.5)
    hi = np.percentile(pc, 97.5)
    return lo, hi


def get_values(df: pd.DataFrame, model: str, dataset: str, col: str) -> np.ndarray:
    return df[(df["model"] == model) & (df["dataset"] == dataset)][col].to_numpy(dtype=float)


# -----------------------------
# Main pipeline
# -----------------------------
def main() -> None:
    ensure_outdir(OUTDIR)

    df = pd.read_csv(RESULTS_CSV)
    # columns: model,dataset,text_id,magnitude,cosine_similarity
    assert {"model", "dataset", "magnitude", "cosine_similarity"}.issubset(df.columns)

    # Optional summary (not required)
    try:
        _ = pd.read_csv(SUMMARY_CSV)
    except Exception:
        pass

    # -----------------------------
    # Group 1 ANOVA (Simple/Moderate/Complex) per model
    # -----------------------------
    anova_rows = []
    kw_rows = []
    for model in MODELS:
        # Magnitude ANOVA
        mag_s = get_values(df, model, G1["simple"], "magnitude")
        mag_m = get_values(df, model, G1["moderate"], "magnitude")
        mag_c = get_values(df, model, G1["complex"], "magnitude")

        f_mag, p_mag = stats.f_oneway(mag_s, mag_m, mag_c)
        eta_mag = eta_squared_oneway(mag_s, mag_m, mag_c)

        # Cosine ANOVA
        cos_s = get_values(df, model, G1["simple"], "cosine_similarity")
        cos_m = get_values(df, model, G1["moderate"], "cosine_similarity")
        cos_c = get_values(df, model, G1["complex"], "cosine_similarity")

        f_cos, p_cos = stats.f_oneway(cos_s, cos_m, cos_c)
        eta_cos = eta_squared_oneway(cos_s, cos_m, cos_c)

        anova_rows.append(
            {
                "model": model,
                "anova_F_magnitude": f_mag,
                "anova_p_magnitude": p_mag,
                "eta2_magnitude": eta_mag,
                "anova_F_cosine": f_cos,
                "anova_p_cosine": p_cos,
                "eta2_cosine": eta_cos,
                "alpha_bonferroni": ALPHA_BONF,
                "mag_sig_bonf": p_mag < ALPHA_BONF,
                "cos_sig_bonf": p_cos < ALPHA_BONF,
            }
        )

        # Kruskal–Wallis robustness
        h_mag, pkw_mag = stats.kruskal(mag_s, mag_m, mag_c)
        h_cos, pkw_cos = stats.kruskal(cos_s, cos_m, cos_c)

        kw_rows.append(
            {
                "model": model,
                "kruskal_H_magnitude": h_mag,
                "kruskal_p_magnitude": pkw_mag,
                "kruskal_H_cosine": h_cos,
                "kruskal_p_cosine": pkw_cos,
                "alpha_bonferroni": ALPHA_BONF,
                "mag_sig_bonf": pkw_mag < ALPHA_BONF,
                "cos_sig_bonf": pkw_cos < ALPHA_BONF,
            }
        )

    anova_table = pd.DataFrame(anova_rows)
    kw_table = pd.DataFrame(kw_rows)

    anova_table.to_csv(f"{OUTDIR}/anova_table.csv", index=False)
    kw_table.to_csv(f"{OUTDIR}/kw_table.csv", index=False)

    # -----------------------------
    # Simple vs Complex Welch tests + effect sizes + % changes
    # -----------------------------
    welch_rows = []
    boot_rows = []

    for model in MODELS:
        # Magnitude: Welch t-test
        x = get_values(df, model, G1["simple"], "magnitude")
        y = get_values(df, model, G1["complex"], "magnitude")
        t_mag, p_mag = stats.ttest_ind(x, y, equal_var=False)
        d_mag = cohen_d_independent(x, y)
        pc_mag = percent_change(np.mean(x), np.mean(y))
        lo_mag, hi_mag = bootstrap_percent_change_ci(x, y)

        # Cosine: Welch t-test
        x2 = get_values(df, model, G1["simple"], "cosine_similarity")
        y2 = get_values(df, model, G1["complex"], "cosine_similarity")
        t_cos, p_cos = stats.ttest_ind(x2, y2, equal_var=False)
        d_cos = cohen_d_independent(x2, y2)
        pc_cos = percent_change(np.mean(x2), np.mean(y2))
        lo_cos, hi_cos = bootstrap_percent_change_ci(x2, y2)

        welch_rows.append(
            {
                "model": model,
                "mag_mean_simple": np.mean(x),
                "mag_mean_complex": np.mean(y),
                "mag_t_welch": t_mag,
                "mag_p_welch": p_mag,
                "mag_cohens_d": d_mag,
                "mag_percent_change": pc_mag,
                "cos_mean_simple": np.mean(x2),
                "cos_mean_complex": np.mean(y2),
                "cos_t_welch": t_cos,
                "cos_p_welch": p_cos,
                "cos_cohens_d": d_cos,
                "cos_percent_change": pc_cos,
                "alpha_bonferroni": ALPHA_BONF,
                "mag_sig_bonf": p_mag < ALPHA_BONF,
                "cos_sig_bonf": p_cos < ALPHA_BONF,
            }
        )

        boot_rows.append(
            {
                "model": model,
                "mag_pc": pc_mag,
                "mag_ci95_lo": lo_mag,
                "mag_ci95_hi": hi_mag,
                "cos_pc": pc_cos,
                "cos_ci95_lo": lo_cos,
                "cos_ci95_hi": hi_cos,
                "bootstrap_B": BOOTSTRAP_B,
                "seed": RNG_SEED,
            }
        )

    welch_table = pd.DataFrame(welch_rows)
    boot_table = pd.DataFrame(boot_rows)

    welch_table.to_csv(f"{OUTDIR}/welch_simple_vs_complex.csv", index=False)
    boot_table.to_csv(f"{OUTDIR}/bootstrap_ci_simple_vs_complex.csv", index=False)

    # -----------------------------
    # Length controls: Group 3 and Group 4 (Short vs Long)
    # -----------------------------
    length_rows = []
    for model in MODELS:
        for grp_name, grp in [("group3_synth", G3), ("group4_real_padded", G4)]:
            # magnitude
            xs = get_values(df, model, grp["short"], "magnitude")
            xl = get_values(df, model, grp["long"], "magnitude")
            t_mag, p_mag = stats.ttest_ind(xs, xl, equal_var=False)
            d_mag = cohen_d_independent(xs, xl)
            pc_mag = percent_change(np.mean(xs), np.mean(xl))
            lo_mag, hi_mag = bootstrap_percent_change_ci(xs, xl)

            # cosine
            cs = get_values(df, model, grp["short"], "cosine_similarity")
            cl = get_values(df, model, grp["long"], "cosine_similarity")
            t_cos, p_cos = stats.ttest_ind(cs, cl, equal_var=False)
            d_cos = cohen_d_independent(cs, cl)
            pc_cos = percent_change(np.mean(cs), np.mean(cl))
            lo_cos, hi_cos = bootstrap_percent_change_ci(cs, cl)

            length_rows.append(
                {
                    "group": grp_name,
                    "model": model,
                    "mag_mean_short": np.mean(xs),
                    "mag_mean_long": np.mean(xl),
                    "mag_t_welch": t_mag,
                    "mag_p_welch": p_mag,
                    "mag_cohens_d": d_mag,
                    "mag_percent_change": pc_mag,
                    "mag_ci95_lo": lo_mag,
                    "mag_ci95_hi": hi_mag,
                    "cos_mean_short": np.mean(cs),
                    "cos_mean_long": np.mean(cl),
                    "cos_t_welch": t_cos,
                    "cos_p_welch": p_cos,
                    "cos_cohens_d": d_cos,
                    "cos_percent_change": pc_cos,
                    "cos_ci95_lo": lo_cos,
                    "cos_ci95_hi": hi_cos,
                }
            )

    length_table = pd.DataFrame(length_rows)
    length_table.to_csv(f"{OUTDIR}/length_controls_group3_group4.csv", index=False)

    # -----------------------------
    # Print a concise console summary
    # -----------------------------
    print("\n=== Bonferroni-corrected alpha across 8 models ===")
    print(f"alpha_bonf = {ALPHA_BONF:.6f}\n")

    print("=== Group 1 ANOVA significance (magnitude, cosine) ===")
    print(anova_table[["model", "anova_p_magnitude", "mag_sig_bonf", "anova_p_cosine", "cos_sig_bonf"]])

    print("\n=== Simple vs Complex Welch tests (p-values) ===")
    print(welch_table[["model", "mag_p_welch", "cos_p_welch", "mag_sig_bonf", "cos_sig_bonf"]])

    print("\nSaved tables to:", OUTDIR)


if __name__ == "__main__":
    main()